Add APNG image support
pinterest/PINRemoteImage pull request #543
Opened 2020-02-28 11:38 UTC by sagesse-cn

for #542

2020-09-08 01:50 UTC, sagesse-cn commented
I'm sorry it took so long

2020-10-07 17:42 UTC, garrettmoon requested changes
I'm sorry you haven't received a review on this!

Two things to start:
 - Would you mind putting this behind a compiler flag like PIN_WEBP? I'm concerned about adding another check in altertnateRepresentationWithData since it needs to run so frequently. Additionally, I'm not sure how common APNG use is?
- Would you mind adding tests to make sure this is working as expected?

2020-10-23 06:39 UTC, sagesse-cn commented
There is only a slight difference between `PINGIFAnimatedImage` and `PINAPNGAnimatedImage`. 
Based a `PINAppleAnimatedImage` would maybe is a better choice.

2022-02-15 02:36 UTC, sagesse-cn commented
@garrettmoon This PR has been suspended for a long time, is there anything not modified?

I have updated the PR to the latest code.

2022-02-15 18:22 UTC, garrettmoon commented
It has been too long, I'm sorry :(

The CI failures may be related to Xcode updates. I think https://github.com/pinterest/PINRemoteImage/pull/616 may have some fixes there?

2022-02-16 02:34 UTC, sagesse-cn commented on Source/Classes/AnimatedImages/PINCachedAnimatedImage.m
> +#import "PINAPNGAnimatedImage.h"
done

2022-02-16 02:34 UTC, sagesse-cn commented on Source/Classes/AnimatedImages/PINCachedAnimatedImage.m
> +    if ([animatedImageData pin_isAPNG]) {
done

2022-02-18 00:15 UTC, sagesse-cn commented
@garrettmoon it's done

2022-02-18 01:07 UTC, garrettmoon commented
Thank you for hanging in there and for the contribution!

2022-02-18 01:07 UTC, merged